final Map<String, String> enUs = {
  "donor_choice_manager": "Donor Choice Manager",

  /// Signin Screen
  "sign_in": "Sign In",
  "fogot_password": "Fogot Password",
  "or_login_with": "or login with",
  "localized_reason": "Authenticate to access the app",

  /// Recover Password Screen
  "recover_password": "Recover Password",
  "enter_the_email":
      "Enter the email associated with your account and we’ll send an confirmation email  to reset your Password.",
  "send_instructions": "Send Instructions",

  /// Reset Password Screen
  "verification": "Verification",
  "the_code_has_been":
      "The code has been sent to your registered email address.",
  "didn_t_recieve_code": "Didn’t recieve Code? ",
  "resend_code": "Resend Code",
  "sending": "Sending",
  "new_password": "New Password",
  "confirm_password": "Confirm Password",
  "reset_password": "Reset Password",

  /// Home Screen
  "select_an_organization": "Select an organization",
  "registered_donors": "Registered Donors",
  "followers": "Followers",
  "total_transactions": "Total Transactions",
  "this_year_transaction": "This Year Transaction",
  "donation_since": "Donation Since",
  "day_donation": "Day Donation",
  "month_donation": "Month Donation",
  "recuring_details": "Recuring Details",
  "campaigns": "Campaigns",
  "campaign_filter": "Campaign Filter",
  "campaign_summary": "Campaign Summary",
  "no_of_transactions": "No. of  transactions",
  "recurring_filter": "Recurring Filter",
  "recurring": "Recurring",

  /// Analytics Screen
  "analytics_information": "Analytics Information and Statistics",
  "total_donations": "Total Donations Amount:",
  "filter_by_number_of_years": "Filter By Number Of Years",
  "number_of_years": "Number of Years",
  "tender_types": "Tender Types",
  "channel_types": "Channel Types",
  "receipt": "Receipt",
  "total_amount_in": "Total Amount in",
  "filter_by_year_and_month": "Filter By Year And Month",
  "transaction": "Transaction",
  "receipted": "Receipted",
  "qrcode_saved": "QR code has been saved successfully in download directory.",

  /// Compaign Screen
  "filter_compaign": "Filter Compaign",
  "delete_campaign": "Delete Campaign",
  "are_you_sure_delete_campaign":
      "Are you sure you want to delete this Campaign?",
  "you_cannot_undo": "You cannot undo this action.",
  "create_campaign": "Create Campaign",
  "add_campaign": "Add Campaign",
  "target_amount": "Target Amount",
  "icons": "Icons",
  "select_icon": "Select an icon for your campaign",
  "name": "Name",
  "donation_campaign": "Donation Campaign",
  "campaign_description": "Description",
  "start_date_and_time": "Start Date and Time",
  "end_date_and_time": "End Date and Time",
  "end_date_time_should_be_greater_than_start_date_time":
      "End Date Time should be greater than Start Date Time",
  "fee": "Fee",
  "issue_tax_receipt": "Issue Tax Receipt",
  "devices": "Devices",
  "create": "Create",
  "update_campaign": "Update Campaign",

  /// Donors Screen
  "filter_donors": "Filter Donors",
  "delete_donor": "Delete Donor",
  "update_donor": "Update Donor",
  "add_donors": "Add Donors",
  "created": "Created",
  "updated": "Updated",
  "first_name": "First Name",
  "middle_name": "Middle Name",
  "last_name": "Last Name",
  "phone": "Phone",
  "street_address": "Street Address",
  "city": "City ",
  "country": "Country",
  "select_country": "Select Country",
  "are_you_sure_delete_donor": "Are you sure you want to delete this Donor?",

  /// Channels Screen
  "channels_summary": "Channels Summary",
  "registered_channels": "Registered Channels",
  "filter_channel": "Filter Channel",
  "update_channel": "Update Channel",
  "channel_name": "Channel Name",

  /// Media Centre Screen
  "update_widget": "Update Widget",
  "widget_value": "Widget Value",
  "delete_media": "Delete Media",
  "filter_media": "Filter Media",
  "add_media": "Add Media",
  "media_center": "Media Center",
  "widgets": "Widgets",
  "update_media": "Update Media",
  "location": "Location",
  "duration": "Duration",
  "full_screen": "Full Screen",
  "muted": "Muted",
  "description": "Description",
  "select_file": "Select file",
  "media_file": "Media (Upload Image/Video files only. Max File Size 20MB)",
  "are_you_sure_delete_media": "Are you sure you want to delete this Media?",

  /// Organization Screen
  "profile": "Profile",
  "address": "Address",
  "supplementary_data": "Supplementary Data",
  "charity": "Charity",
  "contact": "Contact",
  "unit_number": "Unit Number",
  "save": "Save",
  "update_signature": "Update Signature",
  "choose_file": "Choose File",
  "need_to_generate": "Need to Generate Signature?",
  "charity_organization": "Charity Organization",
  "registeration_number": "Registeration Number",
  "tax_receipt_start_date": "Tax Receipt Start Date",
  "tax_receipt_footer": "Tax Receipt Footer",
  "website": "Website",
  "location_name": "Location Name",
  "time_zone": "Time Zone",
  "short_name": "Short Name",
  "receipt_alert_email": "Receipt Alert Email",
  "sign_up_date": "Sign Up Date",
  "last_update": "Last Update",
  "portal_url": "Portal URL",
  "force_registration": "Force Registration",
  "no_file_chosen": "No File Chosen",

  /// Reports Screen
  "select": "Select",
  "generate_report": "Generate Report",
  "report_saved":
      "Report file has been saved successfully in download directory",

  /// Transactions Screen
  "filter_transaction": "Filter Transaction",
  "new_transaction": "New Transaction",
  "download": "Download",
  "use_new_card": "Use New Card",
  "valid_thru": "VALID THRU",
  "scan_card": "Scan Card",
  "card_holder_name": "Card Holder Name",
  "card_number": "Card Number",
  "expiry_month": "Expiry Month",
  "expiry_year": "Expiry Year",
  "ccv": "CVC",
  "save_card": "Save Card",
  "confirm_transaction": "Confirm Transaction",
  "other_information": 'Other Information',
  "donor_email": "Donor Email",
  "billing_period": "Billing Period",
  "no_of_recurring": "No. Of Recurring",
  "cover_transaction_costs": "Cover Transaction Costs",
  "update_email": "Update Email",
  "transaction_details": "Transaction Details",
  "enter_your_email_address": "Enter your Email Address",
  "frequency": "Frequency",
  "no_of_donations": "No. Of Donations",
  "make_this_a_recurring_transaction": "Make this a recurring transaction",
  "specify_number_of_recurring":
      "I want to specify number of recurring payments",
  "minimum_recurrings_02": "Minimum Recurrings: 02",
  "transaction_export":
      "Transactions records file has been saved successfully in download directory.",

  /// Users Screen
  "users": "Users",
  "add_user": "Add User",
  "delete_user": "Delete User",
  "language": "Language",
  "add_users": "Add Users",
  "update_user": "Update User",
  "english": "English",
  "delete_user_message": "Are you sure you want to delete this user?",

  /// Common
  "account": "Account",
  "actions": "Actions",
  "active": "Active",
  "add": "Add",
  "amount": "Amount",
  "analytics": "Analytics",
  "ascending": "Ascending",
  "back": "back",
  "browse": "Browse",
  "campaign": "Campaign",
  "cancel": "Cancel",
  "channels": "Channels",
  "collection": "Collection %",
  "confirm": "Confirm",
  "date": "Date",
  "day": "Day",
  "delete": "Delete",
  "deleting": "Deleting",
  "descending": "Descending",
  "donation": "Donation",
  "donor": "Donor",
  "donors": "Donors",
  "edit": "Edit",
  "email": "Email",
  "email_address": "Email address",
  "end_date": "End Date",
  "filter": "Filter",
  "filter_by_date": "Filter By Date",
  "filter_by_years": "Filter By Years",
  "home": "Home",
  "icon": "Icon",
  "inactive": "Inactive",
  "invoice": "Invoice",
  "logout": "Logout",
  "media_centre": "Media Centre",
  "minimum_amount": "Minimum Amount",
  "month": "Month",
  "more": "More",
  "next": "Next",
  "no": "No",
  "no_records_found": "No Records Found",
  "note": "Note",
  "order_by": "Order by",
  "organization": "Organization",
  "organizations": "Organizations",
  "password": "Password",
  "payment": "Payment",
  "percentage": "Percentage",
  "postal_code": "Postal Code",
  "postal_zip_code": "Postal/Zip code",
  "processing": "Processing",
  "progress": "Progress",
  "province": "Province",
  "qr_code": "QR Code",
  "record_per_page": "Record Per Page",
  "reports": "Reports",
  "reset": "Reset",
  "select...": "Select...",
  "select_fields": "Select Fields",
  "select_month": "Select Month",
  "select_year": "Select Year",
  "sort_by": "Sort by",
  "sort_order": "Sort Order",
  "start_date": "Start Date",
  "state": "State",
  "status": "Status",
  "tax_deductible": "Tax Deductible",
  "tender_type": "Tender Type",
  "total": "Total",
  "total_amount": "Total Amount",
  "transactions": "Transactions",
  "try_again": "Try again",
  "update": "Update",
  "user": "User",
  "version": "Version",
  "write_here...": "Write Here...",
  "year": "Year",
  "yes": "Yes",
  "yyyy-mm-dd": "YYYY-MM-DD",
  "yyyy/mm/dd": "YYYY/MM/DD",
  "zip_code": "Zip Code",
  "media": "Media",
  "notes": "notes",
  "holder_name": "holder name",
  "card": "Card",
  "number": "Number",
  "minimum_recurrings": "Minimum recurrings",

  /// Error
  "network_err": "Network Error",
  "no_internet_found": "No Internet Found!",
  "something_went_wrong": "Something Went Wrong!",
  "the_connection_error": "The connection error",
  "bad_response": "Bad Response",
  "connection_error": "Connection error",
  "sent_timeout": "sent timeout",
  "connection_timeout": "Connection timeout",
  "receiving_timeout": "Receiving timeout",
  "unknown_error": "Unknown error",
  "other_error": "Other error",
  "could_not_launch": "Could not launch",
  "request_is_cancelled": "Request is cancelled",
  "login_first": "Please login first with your email and password",
  "login_via_email_password": "Please login with your email and password",
  "capable": "Sorry your device not capable for biometric authentication",
  "checking_biometrics": "Sorry your device not capable.",
  "enrolled_biometric": "Sorry your device not enrolled biometrics",
  "cant_select_organization": "user can't select this organization",
  "video_not_supported": "Video not supported",
  "media_file_required": "Media file required",
  "media_file_extension_required":
      "For image required format: jpg, jpeg, png, bmp, gif \nFor video required format: mp4",
  "input_is_required": "Input is required",
  "amount_cannot_be_less_then": "Amount cannot be less then",
  "please_enter_your_email": "Please enter your email",
  "please_enter_your_password": "Please enter your password",
  "please_re_enter_your_password_for_confirmation":
      "Please re-enter your password for confirmation",
  "please_enter_the_code_sent_to_your_email":
      "Please enter the code sent to your email",
  "must_be_between_2_to_999": " must be between 2 to 999",
  "please_enter_valid": "Please enter valid",
  "cannot_be_null": "Cannot be null",
  "cannot_be_empty": "Cannot be empty",
  "file_size_exceed": "File size exceeds maximum allowed size (20 MB)",
  "video_resolution_required":
      "Video resolution must be between 16x16 to 1920x1080",
};
